### ISSUE TITLE
Authn_decoupling branch Tyk + Keycloak

### ISSUE THREAD

**Issue by ljdursi** [CanDIG/roadmap#2]
Done when SSO is completely handled by API gateway and services need only validate tokens/session keys

**Comment by ljdursi** [comment]
Remaining to be done:
- [ ] Changes merged to main branch of Candig-compose
- [ ] Documentation

**Comment by amanjeev** [comment]
Work for the above is being done in  https://github.com/CanDIG/candig_compose/pull/21

**Comment by amanjeev** [comment]
Aman: 
- [ ] Document adding claims to keycloak

**Comment by ljdursi** [comment]
- [ ] API keys: adding/removing
